version: '3.9'

services:
  postgres:
    image: con-postgres
    user: ${CON_USER:-1000:1000}
    environment:
      - POSTGRES_USER: ${CON_DB_USER:-postgres}
      - POSTGRES_PASSWORD: ${CON_DB_PASSWORD:-postgres}
      - POSTGRES_DB: ${CON_DB_NAME:-con}
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - ../logs/postgres:/log
      - ../data/postgres:/var/lib/postgresql/data
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    networks:
      con-network: