"""add_datalog_additional

Revision ID: 26503984bdfc
Revises: 944e613d0115
Create Date: 2024-06-30 15:06:42.754655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26503984bdfc'
down_revision: Union[str, None] = '944e613d0115'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datalog', sa.Column('additional', sa.String(), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('datalog', 'additional')
    # ### end Alembic commands ###
