"""create tables

Revision ID: 94ffc72f08c3
Revises: 
Create Date: 2024-03-30 07:47:40.899224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from datetime import datetime
from pytz import timezone

# revision identifiers, used by Alembic.
revision: str = '94ffc72f08c3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hello',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    op.execute(
        sa.text(
            """
            INSERT INTO hello (id, message, created_at, timezone)
            VALUES (:id, :message, :created_at, :timezone)
            """
        ).bindparams(
            sa.bindparam("id", 1),
            sa.bindparam("message", "Hello, World!"),
            sa.bindparam("created_at", datetime.now(timezone('Asia/Tokyo'))),
            sa.bindparam("timezone", "Asia/Tokyo")
        )
    )

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hello')
    # ### end Alembic commands ###
