"""add dashboard

Revision ID: ec62c59fc8fb
Revises: 076746049d6e
Create Date: 2024-05-29 15:31:50.509240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec62c59fc8fb'
down_revision: Union[str, None] = '076746049d6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=True),
    sa.Column('json_data', sa.JSON(), nullable=True),
    sa.Column('updated_by_id', sa.String(length=10), nullable=True),
    sa.Column('created_by_id', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dashboard')
    # ### end Alembic commands ###
