"""add log_color log_memo

Revision ID: fbaf3d6eef63
Revises: 75db3a2e7ab3
Create Date: 2024-04-02 16:06:18.443333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbaf3d6eef63'
down_revision: Union[str, None] = '75db3a2e7ab3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_color',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=100), nullable=False),
    sa.Column('color_name', sa.String(length=7), nullable=False),
    sa.Column('color_code', sa.String(length=30), nullable=False),
    sa.Column('created_by_id', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('created_by_id', 'event', name='uix_1')
    )
    op.create_table('log_memo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('memo', sa.String(length=500), nullable=False),
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['log_id'], ['lifelog.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log_memo')
    op.drop_table('log_color')
    # ### end Alembic commands ###
