version: '3.9'

services:
  backend:
    image: con-backend
    user: ${CON_USER:-1000:1000}
    command: ["gunicorn", "-c", "gunicorn_conf.py", "main:app"]
    volumes:
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - ../logs/backend:/app/log:rw
    networks:
      con-network: